import { Trader, Trade, Strategy } from "@/types";

export const currentUser: Trader = {
  id: "jdtrader",
  handle: "jdtrader",
  displayName: "JD Trader",
  initials: "JD",
  color: "#6366F1",
  brokerage: "TD Ameritrade",
  verified: false,
  followers: 2400,
  following: 318,
  winRate: 72,
  pnlMonth: 34,
  categories: ["Hot strategies", "Most improved"],
};

export const traders: Trader[] = [
  {
    id: "twolfgang",
    handle: "twolfgang",
    displayName: "T Wolfgang",
    initials: "TW",
    color: "#F59E0B",
    brokerage: "Interactive Brokers",
    verified: false,
    followers: 8200,
    following: 120,
    winRate: 81,
    pnlMonth: 4800,
    categories: ["Hot strategies"],
  },
  {
    id: "kmscalper",
    handle: "kmscalper",
    displayName: "KM Scalper",
    initials: "KM",
    color: "#10B981",
    brokerage: "TD Ameritrade",
    verified: false,
    followers: 5100,
    following: 240,
    winRate: 68,
    pnlMonth: 1200,
    categories: ["Hot strategies", "Most improved"],
  },
  {
    id: "sarahreads",
    handle: "sarahreads",
    displayName: "Sarah Reads",
    initials: "SR",
    color: "#8B5CF6",
    brokerage: "IBKR",
    verified: false,
    followers: 3300,
    following: 410,
    winRate: 55,
    pnlMonth: -310,
    categories: ["Unprofitable"],
  },
  {
    id: "newtrader99",
    handle: "newtrader99",
    displayName: "New Trader 99",
    initials: "NT",
    color: "#EC4899",
    brokerage: "Alpaca",
    verified: false,
    followers: 890,
    following: 1200,
    winRate: 61,
    pnlMonth: 620,
    categories: ["Most improved"],
  },
  {
    id: "mikefxpro",
    handle: "mikefxpro",
    displayName: "Mike FX Pro",
    initials: "MF",
    color: "#14B8A6",
    brokerage: "TradeStation",
    verified: false,
    followers: 4400,
    following: 88,
    winRate: 74,
    pnlMonth: 2100,
    categories: ["Hot strategies"],
  },
];

export const feedTrades: Trade[] = [
  {
    id: "t1",
    traderId: "kmscalper",
    ticker: "NVDA",
    direction: "Long",
    shares: 200,
    time: "2 min ago",
    pnl: 1240,
    pnlPct: 6.2,
    notes:
      "Nailed the NVDA breakout at open. Waited for the 9:45 candle confirmation then went in with 200 shares. Scaled out at +$6.20. Classic momentum setup.",
    likes: 84,
    comments: 12,
  },
  {
    id: "t2",
    traderId: "sarahreads",
    ticker: "SPY",
    direction: "Short",
    shares: 10,
    time: "18 min ago",
    pnl: -310,
    pnlPct: -2.1,
    notes:
      "Tough morning on SPY puts. Fed minutes came in hotter than expected and killed the trade. Cutting losses and staying flat for rest of day. Transparency matters.",
    likes: 41,
    comments: 27,
  },
  {
    id: "t3",
    traderId: "twolfgang",
    ticker: "AAPL",
    direction: "Long",
    shares: 500,
    time: "34 min ago",
    pnl: 2870,
    pnlPct: 3.8,
    notes:
      "AAPL reclaimed VWAP after earnings. Held through the dip — conviction in the setup. This is a textbook VWAP reclaim play.",
    likes: 132,
    comments: 45,
  },
  {
    id: "t4",
    traderId: "mikefxpro",
    ticker: "TSLA",
    direction: "Short",
    shares: 100,
    time: "52 min ago",
    pnl: 940,
    pnlPct: 2.2,
    notes:
      "TSLA failed at the 200 SMA again. Shorted the rejection with tight stop above resistance. Covered into support.",
    likes: 67,
    comments: 19,
  },
];

export const strategies: Strategy[] = [
  { id: "gap-and-go", name: "Gap and go", tag: "Hot", winRate: 68, traders: 1240 },
  { id: "vwap-reclaim", name: "VWAP reclaim", tag: "Hot", winRate: 61, traders: 890 },
  { id: "0dte-options", name: "0DTE options", tag: "Cold", winRate: 44, traders: 2100 },
  { id: "earnings-momentum", name: "Earnings momentum", tag: "Rising", winRate: 57, traders: 430 },
  { id: "premarket-breakout", name: "Pre-market breakout", tag: "Hot", winRate: 65, traders: 670 },
];

export const leaderboard = {
  topToday: [
    { rank: 1, trader: traders[0], pnl: 4800 },
    { rank: 2, trader: traders[1], pnl: 1200 },
    { rank: 3, trader: currentUser, pnl: 880 },
  ],
  mostImproved: [
    { trader: traders[3], changePct: 312 },
    { trader: traders[4], changePct: 198 },
  ],
};
